# Generated by Django 5.0.6 on 2024-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('piccture', models.FileField(blank=True, null=True, upload_to='service/')),
            ],
        ),
    ]
