# Generated by Django 5.0.6 on 2024-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_piccture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='piccture',
            field=models.FileField(blank=True, null=True, upload_to='service/'),
        ),
    ]
