# Generated by Django 5.0.6 on 2024-07-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0004_app_appitem_app_app_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appitem',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appitem',
            name='app_service',
        ),
        migrations.DeleteModel(
            name='app',
        ),
        migrations.DeleteModel(
            name='appitem',
        ),
    ]
