# Generated by Django 5.0.6 on 2024-08-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_app_appitem_app_app_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='finalized',
        ),
    ]
