# Generated by Django 5.0.6 on 2024-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_remove_app_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
